# .github/workflows/publish.yml
name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libglib2.0-dev \
            libgobject2.0-dev \
            libglibutil-dev \
            python3-dev \
            git \
            cmake \
            ninja-build \
            meson

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            build \
            twine \
            wheel \
            Cython>=0.29 \
            gitpython>=3.1 \
            pkgconfig \
            meson-python>=0.13.0

      - name: Build source & wheels
        run: |
          rm -rf build dist *.egg-info
          python -m build

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
